### ISSUE TITLE
GettingStarted/Examples/Polaris/affinity page shows "module load llvm-sycl"; should be "module load oneapi"

### ISSUE THREAD

**Issue by monkeystate** [argonne-lcf/GettingStarted#15]
Per discussion w/Software Committee, since there is no longer a llvm-sycl module, the oneapi module should be loaded in its place. As such, instructions on this page need to reflect this change:
https://github.com/argonne-lcf/GettingStarted/tree/master/Examples/Polaris/affinity

**Comment by cjknight** [comment]
Fixed here: #16 . Still need to look through and update user-guides.

**Comment by cjknight** [comment]
I think user-guides is up-to-date after this PR merged: https://github.com/argonne-lcf/user-guides/pull/263 .
