### ISSUE TITLE
Incorrect path to helper script in Aurora batch scripts

### ISSUE THREAD

**Issue by jhux2** [argonne-lcf/GettingStarted#25]
In the Aurora batch scripts `submit_1pergpu.sh`, the path to the helper script `set_affinity_gpu_aurora.sh` is incorrect.  PR #24 fixes this.

**Comment by colleeneb** [comment]
Thanks! [PR#24](https://github.com/argonne-lcf/GettingStarted/pull/24) was merged in so I'm closing this. Let me know if it needs to be reopened for any reason!
