### ISSUE TITLE
sample job scripts reference workq

### ISSUE THREAD

**Issue by zingale** [argonne-lcf/GettingStarted#3]
The sample job scripts reference `workq`, but this is not a queue regular users seem to have access to.  The docs instead refer to `debug` and `prod`, so perhaps the sample scripts here should be updated?

**Comment by cjknight** [comment]
Thanks for catching that! I switched to debug queue in current submit.sh scripts. I need to PBS-ify several other submit scripts and then will merge.

**Comment by cjknight** [comment]
Scripts here and in docs updated to remove workq queue.
